const SHOP_ACTION_TYPES = {
    UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
    SET_CATEGORIES: 'category/SET_CATEGORIES_MAP',
    SET_VIEW_PRODUCT: 'category/SET_VIEW_PRODUCT',
    SET_PRODUCT_DESCRIPTIONS: '/category/SET_PRODUCT_DESCRIPTIONS',
    GET_PRODUCT_DESCRIPTION: '/category/GET_PRODUCT_DESCRIPTION'
}

export default SHOP_ACTION_TYPES