const SHOP_ACTION_TYPES = {
  UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",
  SET_CATEGORIES: "category/SET_CATEGORIES_MAP",
  SET_VIEW_PRODUCT: "category/SET_VIEW_PRODUCT",
  FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "category/FETCH_CATEGORIES_FAILED",
  SET_PRODUCT_DESCRIPTIONS: "/category/SET_PRODUCT_DESCRIPTIONS",
  GET_PRODUCT_DESCRIPTION: "/category/GET_PRODUCT_DESCRIPTION",
};

export default SHOP_ACTION_TYPES;
